# -*- coding: utf-8 -*-
"""XOR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kACaiVScuXeatEgrjL7jcWHpEYwjQJxH
"""

from sklearn.neural_network import MLPClassifier

X = [[0., 0.], [0., 1.], [1., 0.], [1., 1.]]
y = [0, 1, 1, 0]

clf = MLPClassifier(activation = 'relu', hidden_layer_sizes=(2))

clf.fit(X, y)

clf.predict(X)

clf = MLPClassifier(activation = 'relu', hidden_layer_sizes=(2), solver='lbfgs')

clf.fit(X, y)

clf.predict(X)

#Weights of the connections between the input and the hidden layer
clf.coefs_[0]

#Weights of the connections between the Hidden and the output layer
clf.coefs_[1]

#to get the intercepts:
clf.intercepts_

